export enum CancellationReason {
  CLIENT_REQUEST = 'CLIENT_REQUEST',
  SPECIALIST_UNAVAILABLE = 'SPECIALIST_UNAVAILABLE',
  WEATHER = 'WEATHER',
  EMERGENCY = 'EMERGENCY',
  NO_SHOW = 'NO_SHOW',
  OTHER = 'OTHER',
}
