export enum LoyaltyTransactionType {
  EARN = 'EARN',
  REDEEM = 'REDEEM',
  REFERRAL_BONUS = 'REFERRAL_BONUS',
  REFERRAL_REFERRED = 'REFERRAL_REFERRED',
  MEMBERSHIP_BONUS = 'MEMBERSHIP_BONUS',
  MANUAL_ADJUST = 'MANUAL_ADJUST',
  EXPIRE = 'EXPIRE',
}
