export enum RevenueType {
  SERVICE_PAYMENT = 'SERVICE_PAYMENT',
  PRODUCT_SALE = 'PRODUCT_SALE',
  GIFT_CARD = 'GIFT_CARD',
  SUBSCRIPTION = 'SUBSCRIPTION',
  PENALTY = 'PENALTY',
  REFUND = 'REFUND',
  COMMISSION = 'COMMISSION',
  OTHER = 'OTHER',
}
