export enum ServiceCategory {
  COSMETOLOGY = 'COSMETOLOGY',
  MASSAGE = 'MASSAGE',
  INJECTION = 'INJECTION',
  LASER = 'LASER',
  BODY_CONTOURING = 'BODY_CONTOURING',
  HAIR_REMOVAL = 'HAIR_REMOVAL',
  FACIAL = 'FACIAL',
  OTHER = 'OTHER',
}
