'use client';

import * as React from 'react';

export type Lang = 'ru' | 'en';

interface LanguageCtx {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const RU: Record<string, string> = {
  // ─── Navigation ──────────────────────────────────────────────────────────────
  'nav.dashboard': 'Дашборд',
  'nav.operations': 'Операционный центр',
  'nav.bookings': 'Записи',
  'nav.clients': 'Клиенты',
  'nav.specialists': 'Специалисты',
  'nav.services': 'Услуги',
  'nav.analytics': 'Аналитика',
  'nav.sales': 'Продажи',
  'nav.inventory': 'Склад',
  'nav.finance': 'Финансы',
  'nav.executive': 'Аналитика CEO',
  'nav.chat': 'Чат',
  'nav.settings': 'Настройки',

  // ─── Page titles ──────────────────────────────────────────────────────────────
  'page.dashboard': 'Дашборд',
  'page.bookings': 'Записи',
  'page.clients': 'Клиенты',
  'page.specialists': 'Специалисты',
  'page.services': 'Услуги',
  'page.analytics': 'Аналитика',
  'page.sales': 'Продажи',
  'page.chat': 'Чат',
  'page.profile': 'Профиль',
  'page.settings': 'Настройки',

  // ─── Header ───────────────────────────────────────────────────────────────────
  'header.admin': 'Администратор',
  'header.role': 'admin',
  'header.theme.light': 'Светлая тема',
  'header.theme.dark': 'Тёмная тема',
  'header.notifications': 'Уведомления',
  'header.notifications.empty': 'Нет новых уведомлений',
  'header.notifications.pending': 'записей ожидают подтверждения',
  'header.profile': 'Меню пользователя',
  'header.myProfile': 'Профиль',
  'header.logout': 'Выйти',

  // ─── Common ───────────────────────────────────────────────────────────────────
  'common.loading': 'Загрузка...',
  'common.error': 'Ошибка',
  'common.retry': 'Повторить',
  'common.refresh': 'Обновить',
  'common.noData': 'Нет данных',
  'common.save': 'Сохранить',
  'common.cancel': 'Отмена',
  'common.add': 'Добавить',
  'common.edit': 'Редактировать',
  'common.delete': 'Удалить',
  'common.search': 'Поиск',
  'common.filter': 'Фильтр',
  'common.export': 'Экспорт',
  'common.all': 'Все',
  'common.active': 'Активные',
  'common.inactive': 'Неактивные',
  'common.yes': 'Да',
  'common.no': 'Нет',
  'common.dashboard': 'Дашборд',
  'common.actions': 'Действия',
  'common.status': 'Статус',
  'common.name': 'Название',
  'common.date': 'Дата',
  'common.amount': 'Сумма',
  'common.min': 'мин',

  // ─── Dashboard ────────────────────────────────────────────────────────────────
  'dashboard.greeting.night': 'Доброй ночи',
  'dashboard.greeting.morning': 'Доброе утро',
  'dashboard.greeting.afternoon': 'Добрый день',
  'dashboard.greeting.evening': 'Добрый вечер',
  'dashboard.subtitle': 'Вот что происходит в вашей студии сегодня',
  'dashboard.bookings.total': 'Записи сегодня',
  'dashboard.bookings.cosmetology': 'Косметология',
  'dashboard.bookings.massage': 'Массаж',
  'dashboard.bookings.completed': 'завершено',
  'dashboard.bookings.upcoming': 'предстоит',
  'dashboard.bookings.cancelled': 'отменено',
  'dashboard.trend.vsYesterday': 'vs вчера',
  'dashboard.trend.vsLastWeek': 'vs пр. неделя',
  'dashboard.revenue.today': 'Выручка сегодня',
  'dashboard.revenue.week': 'За неделю',
  'dashboard.revenue.breakdown': 'разбивка по типу',
  'dashboard.specialists.working': 'Работают сегодня',
  'dashboard.specialists.ofTotal': 'из {n} активных',
  'dashboard.workload.title': 'Нагрузка массажистов',
  'dashboard.workload.below': '{n} специалистов ниже нормы',
  'dashboard.workload.met': '✓ Норма выполнена',
  'dashboard.workload.subtitle': 'Минимум {n} сеансов в день',
  'dashboard.workload.viewAll': 'Смотреть специалистов →',
  'dashboard.schedule': 'Расписание',
  'dashboard.newBooking': 'Запись',
  'dashboard.clients': 'Клиенты',
  'dashboard.viewAll': 'Все записи →',
  'dashboard.noAppointments': 'На сегодня записей нет',
  'dashboard.createBooking': 'Создать запись',
  'dashboard.openSchedule': 'Открыть расписание',
  'dashboard.todaySchedule': 'Записи на сегодня',
  'dashboard.todayStats': '{total} записей · {completed} завершено · {upcoming} предстоит',
  'dashboard.error.stale': 'Данные могут быть устаревшими',
  'dashboard.error.retry': 'Обновить',
  'dashboard.statCards.bookings': 'Записи сегодня',
  'dashboard.statCards.bookingsSub': '{n} ожидают подтверждения',
  'dashboard.statCards.revenue': 'Выручка за неделю',
  'dashboard.statCards.revenueSub': 'завершённые записи',
  'dashboard.statCards.revenueTrend': 'vs пред. неделя',
  'dashboard.statCards.specialists': 'Специалистов активных',
  'dashboard.statCards.specialistsSub': '{n} работают сегодня',

  // ─── Operations Center ────────────────────────────────────────────────────────
  'ops.title': 'Операционный центр',
  'ops.subtitle': 'Живое управление салоном',
  'ops.breadcrumb': 'Операционный центр',
  'ops.lastUpdated': 'Последнее обновление',
  'ops.refreshIn': 'Обновление через {n}с',
  'ops.refresh': 'Обновить',
  'ops.retry': 'Повторить',
  // Tabs
  'ops.tab.queue': 'Очередь',
  'ops.tab.specialists': 'Специалисты',
  'ops.tab.rooms': 'Кабинеты',
  'ops.tab.timeline': 'Хронология',
  // Statuses
  'ops.status.pending': 'Ожидает',
  'ops.status.confirmed': 'Подтверждено',
  'ops.status.arrived': 'Прибыл',
  'ops.status.waiting': 'В ожидании',
  'ops.status.in_progress': 'В процессе',
  'ops.status.completed': 'Завершено',
  'ops.status.cancelled': 'Отменено',
  'ops.status.no_show': 'Неявка',
  'ops.status.rescheduled': 'Перенесено',
  // Actions
  'ops.action.confirm': 'Подтвердить',
  'ops.action.checkin': 'Прибыл',
  'ops.action.noshow': 'Неявка',
  'ops.action.cancel': 'Отменить',
  'ops.action.start': 'Начать',
  'ops.action.complete': 'Завершить',
  // Types
  'ops.type.massage': 'Массаж',
  'ops.type.cosmetology': 'Косметология',
  // Live statuses
  'ops.live.free': 'Свободен',
  'ops.live.busy': 'Занят',
  'ops.live.overbooked': 'Перегрузка',
  'ops.live.offline': 'Офлайн',
  // Room
  'ops.room.type.massage': 'Массаж',
  'ops.room.type.cosmetology': 'Косметология',
  'ops.room.type.general': 'Общий',
  'ops.room.occupied': 'Занят',
  'ops.room.free': 'Свободен',
  'ops.room.availableFrom': 'Свободен с',
  'ops.room.availableNow': 'Доступен сейчас',
  'ops.room.bookingsToday': 'записей сегодня',
  'ops.room.empty': 'Кабинеты не настроены',
  'ops.room.emptyHint': 'Добавьте кабинеты через настройки',
  // Alerts
  'ops.alert.late_client': 'Клиент опаздывает',
  'ops.alert.overrun_procedure': 'Превышение времени',
  'ops.alert.long_wait': 'Долгое ожидание',
  'ops.alert.room_conflict': 'Конфликт кабинета',
  'ops.alert.specialist_overloaded': 'Перегрузка специалиста',
  'ops.alert.massage_overload': 'Перегрузка массажиста',
  'ops.alert.critical': 'Критические оповещения',
  // Specialist
  'ops.specialist.now': 'Сейчас:',
  'ops.specialist.next': 'Следующий:',
  'ops.specialist.today': 'Сегодня',
  'ops.specialist.sessions': 'сеансов',
  'ops.specialist.load': 'Нагрузка',
  'ops.specialist.units': 'ед.',
  'ops.specialist.notFound': 'Специалисты не найдены',
  // Queue
  'ops.filter.all': 'Все',
  'ops.queue.empty': 'Записей не найдено',
  // Timeline
  'ops.timeline.specialist': 'Специалист',
  'ops.timeline.empty': 'Нет данных для хронологии',
  // Metrics
  'ops.metrics.total': 'Всего',
  'ops.metrics.inProgress': 'В процессе',
  'ops.metrics.waiting': 'В ожидании',
  'ops.metrics.completed': 'Завершено',
  'ops.metrics.noShow': 'Неявок',
  'ops.metrics.alerts': 'Алерты',
  'ops.metrics.avgWait': 'Ср. ожидание',
  // Delay/wait badges
  'ops.late': 'опаздывает',
  'ops.waiting': 'ожидает',

  // ─── Bookings ─────────────────────────────────────────────────────────────────
  'bookings.title': 'Записи',
  'bookings.new': 'Новая запись',
  'bookings.analytics': 'Аналитика',
  'bookings.export': 'Экспорт',
  'bookings.exporting': 'Экспорт...',
  'bookings.excel': 'Excel',
  'bookings.status.all': 'Все',
  'bookings.status.pending': 'Ожидание',
  'bookings.status.confirmed': 'Подтверждено',
  'bookings.status.in_progress': 'В процессе',
  'bookings.status.completed': 'Завершено',
  'bookings.status.cancelled': 'Отменено',
  'bookings.status.no_show': 'Неявка',
  'bookings.period.today': 'Сегодня',
  'bookings.period.tomorrow': 'Завтра',
  'bookings.period.week': 'Эта неделя',
  'bookings.period.past': 'Прошедшие',
  'bookings.period.future': 'Будущие',
  'bookings.period.all': 'Все даты',
  'bookings.view.week': 'Неделя',
  'bookings.view.month': 'Месяц',
  'bookings.view.year': 'Год',
  'bookings.pickDate': 'Выберите дату',
  'bookings.loading': 'Загрузка...',
  'bookings.count': 'Записей',
  'bookings.chartRevenue': 'Выручка (₽)',
  'bookings.chartCount': 'Количество записей',
  'bookings.heatmap.less': 'Меньше',
  'bookings.heatmap.more': 'Больше',
  'bookings.days.mon': 'Пн',
  'bookings.days.tue': 'Вт',
  'bookings.days.wed': 'Ср',
  'bookings.days.thu': 'Чт',
  'bookings.days.fri': 'Пт',
  'bookings.days.sat': 'Сб',
  'bookings.days.sun': 'Вс',
  'bookings.months.jan': 'Янв',
  'bookings.months.feb': 'Фев',
  'bookings.months.mar': 'Мар',
  'bookings.months.apr': 'Апр',
  'bookings.months.may': 'Май',
  'bookings.months.jun': 'Июн',
  'bookings.months.jul': 'Июл',
  'bookings.months.aug': 'Авг',
  'bookings.months.sep': 'Сен',
  'bookings.months.oct': 'Окт',
  'bookings.months.nov': 'Ноя',
  'bookings.months.dec': 'Дек',

  // ─── Analytics ────────────────────────────────────────────────────────────────
  'analytics.title': 'Аналитика',
  'analytics.subtitle': 'Операционная отчётность студии',
  'analytics.tab.finance': 'Финансы',
  'analytics.tab.massage': 'Нагрузка массажистов',
  'analytics.period.1d': '1 день',
  'analytics.period.7d': '7 дней',
  'analytics.period.1m': '1 месяц',
  'analytics.period.3m': '3 месяца',
  'analytics.period.6m': '6 месяцев',
  'analytics.period.1y': '1 год',
  'analytics.allSpecialists': 'Все специалисты',
  'analytics.metrics.revenue': 'Выручка',
  'analytics.metrics.total': 'Всего записей',
  'analytics.metrics.completed': 'Завершено',
  'analytics.metrics.avgTicket': 'Средний чек',
  'analytics.metrics.clients': 'Клиентов за период',
  'analytics.metrics.newClients': 'Новые клиенты',
  'analytics.metrics.returning': 'Возвратные',
  'analytics.metrics.retention': 'Удержание',
  'analytics.noData': 'Нет данных за выбранный период',
  // Financial analytics (B6)
  'analytics.financial.title': 'Финансовая аналитика',
  'analytics.financial.subtitle': 'Выручка, категории, прогноз',
  'analytics.financial.revenue': 'Выручка',
  'analytics.financial.sessions': 'Сеансов',
  'analytics.financial.avgTicket': 'Средний чек',
  'analytics.financial.topDay': 'Лучший день',
  'analytics.financial.byCategory': 'По категориям',
  'analytics.financial.peakHours': 'Пиковые часы',
  'analytics.financial.forecast': 'Прогноз на 7 дней',
  'analytics.financial.confidence': 'Точность',
  // Massage workload (B6)
  'analytics.massage.title': 'Нагрузка массажистов',
  'analytics.massage.subtitle': 'Контроль выработки и управление нормами',
  'analytics.massage.total': 'Всего массажистов',
  'analytics.massage.working': 'Работают сегодня',
  'analytics.massage.meetingTarget': 'Выполняют норму',
  'analytics.massage.belowTarget': 'Ниже нормы',
  'analytics.massage.overridden': 'Норма снята',
  'analytics.massage.alerts': 'Предупреждения',
  'analytics.massage.specialists': 'Специалисты',

  // ─── Specialists ──────────────────────────────────────────────────────────────
  'specialists.title': 'Специалисты',
  'specialists.add': 'Добавить специалиста',
  'specialists.new': 'Новый специалист',
  'specialists.loading': 'Загрузка...',
  'specialists.empty': 'Специалисты не найдены',
  'specialists.filter.all': 'Все',
  'specialists.filter.active': 'Активные',
  'specialists.filter.inactive': 'Неактивные',
  'specialists.status.active': 'Активен',
  'specialists.status.vacation': 'Отпуск',
  'specialists.status.inactive': 'Неактивен',
  'specialists.status.dismissed': 'Уволен',
  'specialists.deactivate': 'Деактивировать',
  'specialists.restore': 'Восстановить',
  'specialists.experience': 'Опыт: {n} лет',
  'specialists.profile': 'Профиль специалиста →',

  // ─── Services ─────────────────────────────────────────────────────────────────
  'services.title': 'Услуги',
  'services.active': 'Активных',
  'services.total': 'Всего',
  'services.add': 'Новая услуга',
  'services.edit': 'Редактировать услугу',
  'services.loading': 'Загрузка...',
  'services.empty': 'Услуги не найдены',
  'services.hideInactive': 'Скрыть неактивные',
  'services.showAll': 'Показать все',
  'services.col.name': 'Название',
  'services.col.category': 'Категория',
  'services.col.duration': 'Длительность',
  'services.col.price': 'Цена',
  'services.col.status': 'Статус',
  'services.col.actions': 'Действия',
  'services.status.active': 'Активна',
  'services.status.inactive': 'Неактивна',
  'services.cat.cosmetology': 'Косметология',
  'services.cat.massage': 'Массаж',
  'services.cat.injection': 'Инъекции',
  'services.cat.laser': 'Лазер',
  'services.cat.body': 'Коррекция тела',
  'services.cat.epilation': 'Депиляция',
  'services.cat.facial': 'Уход за лицом',
  'services.cat.other': 'Другое',
  'services.cat.consultation': 'Консультация',

  // ─── Sales ────────────────────────────────────────────────────────────────────
  'sales.title': 'Продажи',
  'sales.subtitle': 'Финансовая аналитика и рейтинг сотрудников',
  'sales.record': 'Записать продажу',
  'sales.period.today': 'Сегодня',
  'sales.period.7d': '7 дней',
  'sales.period.30d': '30 дней',
  'sales.period.90d': '90 дней',
  'sales.metrics.revenue': 'Выручка за период',
  'sales.metrics.bookings': 'Записей за период',
  'sales.metrics.avgTicket': 'Средний чек',
  'sales.metrics.conversion': 'Конверсия',
  'sales.metrics.clients': 'Уникальных клиентов',
  'sales.metrics.newClients': 'Новые клиенты',
  'sales.metrics.returning': 'Возвратные клиенты',
  'sales.chart.revenue': 'Динамика выручки',
  'sales.chart.revenueHint': 'Подтверждённые и завершённые записи',
  'sales.chart.bookings': 'Записи по дням',
  'sales.chart.bookingsHint': 'Количество подтверждённых записей',
  'sales.ranking.title': 'Рейтинг продавцов',
  'sales.ranking.hint': 'По атрибутированной выручке за период',
  'sales.noData': 'Нет данных за выбранный период',
  'sales.noDataHint': 'Назначьте продавца при записи',

  // ─── Inventory ────────────────────────────────────────────────────────────────
  'inventory.title': 'Склад',
  'inventory.items': 'Позиций',
  'inventory.loading': 'Загрузка...',
  'inventory.add': 'Добавить',
  'inventory.movement': 'Движение',
  'inventory.edit': 'Изменить',
  'inventory.tab.items': 'Позиции',
  'inventory.tab.alerts': 'Уведомления',
  'inventory.tab.bindings': 'Привязки расходников',
  'inventory.tab.analytics': 'Аналитика',
  'inventory.filter.all': 'Все категории',
  'inventory.search': 'Поиск по названию, SKU, поставщику...',
  'inventory.bindService': 'Привязать расходник',
  'inventory.selectService': 'Выберите услугу',
  'inventory.selectItem': 'Выберите позицию',
  'inventory.status.ok': 'В норме',
  'inventory.status.low': 'Мало',
  'inventory.status.critical': 'Критично',
  'inventory.status.out': 'Нет',
  'inventory.kpi.value': 'Стоимость склада',
  'inventory.kpi.lowStock': 'Мало / Нет',
  'inventory.kpi.expiring': 'Истекает (30 дн)',
  'inventory.cat.injectables': 'Инъектаблы',
  'inventory.cat.skincare': 'Уходовая косметика',
  'inventory.cat.cosm': 'Косметологические расходники',
  'inventory.cat.massageOils': 'Массажные масла',
  'inventory.cat.massageSupp': 'Массажные расходники',
  'inventory.cat.general': 'Общие расходники',
  'inventory.unit.ml': 'мл',
  'inventory.unit.pcs': 'шт',
  'inventory.unit.g': 'г',
  'inventory.unit.kg': 'кг',
  'inventory.unit.l': 'л',
  'inventory.unit.pack': 'упак',
  'inventory.unit.pairs': 'пар',
  'inventory.unit.roll': 'рул',

  // ─── Finance ──────────────────────────────────────────────────────────────────
  'finance.title': 'Финансовый центр',
  'finance.subtitle': 'Платежи · Расходы · Отчётность · Экспорт',
  'finance.tab.payments': 'Платежи',
  'finance.tab.closing': 'Закрытие дня',
  'finance.tab.expenses': 'Расходы',
  'finance.tab.reports': 'Отчёты',
  'finance.tab.export': 'Экспорт',
  'finance.refresh': 'Обновить',
  'finance.acceptPayment': 'Принять платёж',
  'finance.refund': 'Возврат платежа',
  'finance.refundAction': 'Оформить возврат',
  'finance.closeDate': 'Дата закрытия',
  'finance.generate': 'Сформировать',
  'finance.revenueByMethod': 'Выручка по методу',
  'finance.total.received': 'Принято',
  'finance.total.refunded': 'Возвращено',
  'finance.total.net': 'Нетто',
  'finance.total.transactions': 'Транзакций',
  'finance.method.cash': 'Наличные',
  'finance.method.card': 'Карта',
  'finance.method.transfer': 'Перевод',
  'finance.method.yookassa': 'ЮKassa',
  'finance.method.robokassa': 'Robokassa',
  'finance.method.internal': 'Внутренний',
  'finance.payStatus.unpaid': 'Не оплачено',
  'finance.payStatus.deposit': 'Задаток',
  'finance.payStatus.partial': 'Частично',
  'finance.payStatus.paid': 'Оплачено',
  'finance.payStatus.refunded': 'Возврат',
  'finance.payStatus.failed': 'Ошибка',
  'finance.expense.purchase': 'Закупка товаров',
  'finance.expense.rent': 'Аренда',
  'finance.expense.utilities': 'Коммунальные',
  'finance.expense.salary': 'Зарплата',
  'finance.expense.operational': 'Операционные',
  'finance.expense.marketing': 'Маркетинг',
  'finance.expense.other': 'Прочее',

  // ─── Settings ─────────────────────────────────────────────────────────────────
  'settings.title': 'Настройки',
  'settings.subtitle': 'Персонализация и параметры системы',
  'settings.section.interface': 'Внешний вид',
  'settings.section.interfaceSub': 'Интерфейс, тема и плотность',
  'settings.uiMode': 'Режим интерфейса',
  'settings.uiModeSub': 'Выберите рабочее пространство',
  'settings.classic': 'Классический CRM',
  'settings.luxury': 'Luxury Executive',
  'settings.colorTheme': 'Цветовая тема',
  'settings.colorThemeSub': 'Применяется к обоим режимам',
  'settings.dark': 'Тёмная',
  'settings.light': 'Светлая',
  'settings.density': 'Плотность',
  'settings.comfortable': 'Комфортный',
  'settings.compact': 'Компактный',
  'settings.language': 'Язык',
  'settings.langRu': 'Русский',
  'settings.langEn': 'English',
  'settings.section.notifications': 'Уведомления клиентам',
  'settings.section.specialistNotif': 'Уведомления специалистам',
  'settings.notif.confirmation': 'Подтверждение записи',
  'settings.notif.reminder': 'Напоминание за 24 часа',
  'settings.notif.cancellation': 'Уведомление об отмене',
  'settings.notif.sms': 'SMS-уведомления',
  'settings.notif.newBooking': 'Новая запись',
  'settings.notif.cancelReschedule': 'Отмена или перенос',
  'settings.notif.morningBrief': 'Утренняя сводка',
  'settings.section.payment': 'Оплата',
  'settings.payment.cash': 'Наличные',
  'settings.payment.terminal': 'Банковский терминал',
  'settings.payment.online': 'Онлайн-оплата',
  'settings.section.about': 'О студии',
  'settings.section.security': 'Безопасность',
};

const EN: Record<string, string> = {
  // ─── Navigation ──────────────────────────────────────────────────────────────
  'nav.dashboard': 'Dashboard',
  'nav.operations': 'Operations Center',
  'nav.bookings': 'Bookings',
  'nav.clients': 'Clients',
  'nav.specialists': 'Specialists',
  'nav.services': 'Services',
  'nav.analytics': 'Analytics',
  'nav.sales': 'Sales',
  'nav.inventory': 'Inventory',
  'nav.finance': 'Finance',
  'nav.executive': 'Executive',
  'nav.chat': 'Chat',
  'nav.settings': 'Settings',

  // ─── Page titles ──────────────────────────────────────────────────────────────
  'page.dashboard': 'Dashboard',
  'page.bookings': 'Bookings',
  'page.clients': 'Clients',
  'page.specialists': 'Specialists',
  'page.services': 'Services',
  'page.analytics': 'Analytics',
  'page.sales': 'Sales',
  'page.chat': 'Chat',
  'page.profile': 'Profile',
  'page.settings': 'Settings',

  // ─── Header ───────────────────────────────────────────────────────────────────
  'header.admin': 'Administrator',
  'header.role': 'admin',
  'header.theme.light': 'Light theme',
  'header.theme.dark': 'Dark theme',
  'header.notifications': 'Notifications',
  'header.notifications.empty': 'No new notifications',
  'header.notifications.pending': 'bookings awaiting confirmation',
  'header.profile': 'User menu',
  'header.myProfile': 'Profile',
  'header.logout': 'Sign out',

  // ─── Common ───────────────────────────────────────────────────────────────────
  'common.loading': 'Loading...',
  'common.error': 'Error',
  'common.retry': 'Retry',
  'common.refresh': 'Refresh',
  'common.noData': 'No data',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.add': 'Add',
  'common.edit': 'Edit',
  'common.delete': 'Delete',
  'common.search': 'Search',
  'common.filter': 'Filter',
  'common.export': 'Export',
  'common.all': 'All',
  'common.active': 'Active',
  'common.inactive': 'Inactive',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.dashboard': 'Dashboard',
  'common.actions': 'Actions',
  'common.status': 'Status',
  'common.name': 'Name',
  'common.date': 'Date',
  'common.amount': 'Amount',
  'common.min': 'min',

  // ─── Dashboard ────────────────────────────────────────────────────────────────
  'dashboard.greeting.night': 'Good night',
  'dashboard.greeting.morning': 'Good morning',
  'dashboard.greeting.afternoon': 'Good afternoon',
  'dashboard.greeting.evening': 'Good evening',
  'dashboard.subtitle': "Here's what's happening in your studio today",
  'dashboard.bookings.total': "Today's Bookings",
  'dashboard.bookings.cosmetology': 'Cosmetology',
  'dashboard.bookings.massage': 'Massage',
  'dashboard.bookings.completed': 'completed',
  'dashboard.bookings.upcoming': 'upcoming',
  'dashboard.bookings.cancelled': 'cancelled',
  'dashboard.trend.vsYesterday': 'vs yesterday',
  'dashboard.trend.vsLastWeek': 'vs last week',
  'dashboard.revenue.today': "Today's Revenue",
  'dashboard.revenue.week': 'This Week',
  'dashboard.revenue.breakdown': 'by type',
  'dashboard.specialists.working': 'Working Today',
  'dashboard.specialists.ofTotal': 'of {n} active',
  'dashboard.workload.title': 'Massage Workload',
  'dashboard.workload.below': '{n} specialists below target',
  'dashboard.workload.met': '✓ Target met',
  'dashboard.workload.subtitle': 'Minimum {n} sessions per day',
  'dashboard.workload.viewAll': 'View specialists →',
  'dashboard.schedule': 'Schedule',
  'dashboard.newBooking': 'Booking',
  'dashboard.clients': 'Clients',
  'dashboard.viewAll': 'All bookings →',
  'dashboard.noAppointments': 'No bookings for today',
  'dashboard.createBooking': 'Create booking',
  'dashboard.openSchedule': 'Open schedule',
  'dashboard.todaySchedule': "Today's Bookings",
  'dashboard.todayStats': '{total} bookings · {completed} completed · {upcoming} upcoming',
  'dashboard.error.stale': 'Data may be outdated',
  'dashboard.error.retry': 'Retry',
  'dashboard.statCards.bookings': "Today's Bookings",
  'dashboard.statCards.bookingsSub': '{n} awaiting confirmation',
  'dashboard.statCards.revenue': 'Weekly Revenue',
  'dashboard.statCards.revenueSub': 'completed bookings',
  'dashboard.statCards.revenueTrend': 'vs last week',
  'dashboard.statCards.specialists': 'Active Specialists',
  'dashboard.statCards.specialistsSub': '{n} working today',

  // ─── Operations Center ────────────────────────────────────────────────────────
  'ops.title': 'Operations Center',
  'ops.subtitle': 'Live Studio Management',
  'ops.breadcrumb': 'Operations Center',
  'ops.lastUpdated': 'Last updated',
  'ops.refreshIn': 'Refreshing in {n}s',
  'ops.refresh': 'Refresh',
  'ops.retry': 'Retry',
  // Tabs
  'ops.tab.queue': 'Queue',
  'ops.tab.specialists': 'Specialists',
  'ops.tab.rooms': 'Rooms',
  'ops.tab.timeline': 'Timeline',
  // Statuses
  'ops.status.pending': 'Pending',
  'ops.status.confirmed': 'Confirmed',
  'ops.status.arrived': 'Arrived',
  'ops.status.waiting': 'Waiting',
  'ops.status.in_progress': 'In Progress',
  'ops.status.completed': 'Completed',
  'ops.status.cancelled': 'Cancelled',
  'ops.status.no_show': 'No Show',
  'ops.status.rescheduled': 'Rescheduled',
  // Actions
  'ops.action.confirm': 'Confirm',
  'ops.action.checkin': 'Check In',
  'ops.action.noshow': 'No Show',
  'ops.action.cancel': 'Cancel',
  'ops.action.start': 'Start',
  'ops.action.complete': 'Complete',
  // Types
  'ops.type.massage': 'Massage',
  'ops.type.cosmetology': 'Cosmetology',
  // Live statuses
  'ops.live.free': 'Free',
  'ops.live.busy': 'Busy',
  'ops.live.overbooked': 'Overbooked',
  'ops.live.offline': 'Offline',
  // Room
  'ops.room.type.massage': 'Massage',
  'ops.room.type.cosmetology': 'Cosmetology',
  'ops.room.type.general': 'General',
  'ops.room.occupied': 'Occupied',
  'ops.room.free': 'Free',
  'ops.room.availableFrom': 'Free from',
  'ops.room.availableNow': 'Available now',
  'ops.room.bookingsToday': 'bookings today',
  'ops.room.empty': 'No rooms configured',
  'ops.room.emptyHint': 'Add rooms in settings',
  // Alerts
  'ops.alert.late_client': 'Late Client',
  'ops.alert.overrun_procedure': 'Time Overrun',
  'ops.alert.long_wait': 'Long Wait',
  'ops.alert.room_conflict': 'Room Conflict',
  'ops.alert.specialist_overloaded': 'Specialist Overloaded',
  'ops.alert.massage_overload': 'Massage Overload',
  'ops.alert.critical': 'Critical Alerts',
  // Specialist
  'ops.specialist.now': 'Now:',
  'ops.specialist.next': 'Next:',
  'ops.specialist.today': 'Today',
  'ops.specialist.sessions': 'sessions',
  'ops.specialist.load': 'Workload',
  'ops.specialist.units': 'units',
  'ops.specialist.notFound': 'No specialists found',
  // Queue
  'ops.filter.all': 'All',
  'ops.queue.empty': 'No bookings found',
  // Timeline
  'ops.timeline.specialist': 'Specialist',
  'ops.timeline.empty': 'No timeline data',
  // Metrics
  'ops.metrics.total': 'Total',
  'ops.metrics.inProgress': 'In Progress',
  'ops.metrics.waiting': 'Waiting',
  'ops.metrics.completed': 'Completed',
  'ops.metrics.noShow': 'No Shows',
  'ops.metrics.alerts': 'Alerts',
  'ops.metrics.avgWait': 'Avg. wait',
  // Delay/wait badges
  'ops.late': 'late',
  'ops.waiting': 'waiting',

  // ─── Bookings ─────────────────────────────────────────────────────────────────
  'bookings.title': 'Bookings',
  'bookings.new': 'New Booking',
  'bookings.analytics': 'Analytics',
  'bookings.export': 'Export',
  'bookings.exporting': 'Exporting...',
  'bookings.excel': 'Excel',
  'bookings.status.all': 'All',
  'bookings.status.pending': 'Pending',
  'bookings.status.confirmed': 'Confirmed',
  'bookings.status.in_progress': 'In Progress',
  'bookings.status.completed': 'Completed',
  'bookings.status.cancelled': 'Cancelled',
  'bookings.status.no_show': 'No Show',
  'bookings.period.today': 'Today',
  'bookings.period.tomorrow': 'Tomorrow',
  'bookings.period.week': 'This Week',
  'bookings.period.past': 'Past',
  'bookings.period.future': 'Future',
  'bookings.period.all': 'All dates',
  'bookings.view.week': 'Week',
  'bookings.view.month': 'Month',
  'bookings.view.year': 'Year',
  'bookings.pickDate': 'Pick a date',
  'bookings.loading': 'Loading...',
  'bookings.count': 'Bookings',
  'bookings.chartRevenue': 'Revenue (₽)',
  'bookings.chartCount': 'Number of bookings',
  'bookings.heatmap.less': 'Less',
  'bookings.heatmap.more': 'More',
  'bookings.days.mon': 'Mon',
  'bookings.days.tue': 'Tue',
  'bookings.days.wed': 'Wed',
  'bookings.days.thu': 'Thu',
  'bookings.days.fri': 'Fri',
  'bookings.days.sat': 'Sat',
  'bookings.days.sun': 'Sun',
  'bookings.months.jan': 'Jan',
  'bookings.months.feb': 'Feb',
  'bookings.months.mar': 'Mar',
  'bookings.months.apr': 'Apr',
  'bookings.months.may': 'May',
  'bookings.months.jun': 'Jun',
  'bookings.months.jul': 'Jul',
  'bookings.months.aug': 'Aug',
  'bookings.months.sep': 'Sep',
  'bookings.months.oct': 'Oct',
  'bookings.months.nov': 'Nov',
  'bookings.months.dec': 'Dec',

  // ─── Analytics ────────────────────────────────────────────────────────────────
  'analytics.title': 'Analytics',
  'analytics.subtitle': 'Studio operational reporting',
  'analytics.tab.finance': 'Finance',
  'analytics.tab.massage': 'Massage Workload',
  'analytics.period.1d': '1 day',
  'analytics.period.7d': '7 days',
  'analytics.period.1m': '1 month',
  'analytics.period.3m': '3 months',
  'analytics.period.6m': '6 months',
  'analytics.period.1y': '1 year',
  'analytics.allSpecialists': 'All specialists',
  'analytics.metrics.revenue': 'Revenue',
  'analytics.metrics.total': 'Total bookings',
  'analytics.metrics.completed': 'Completed',
  'analytics.metrics.avgTicket': 'Avg ticket',
  'analytics.metrics.clients': 'Clients in period',
  'analytics.metrics.newClients': 'New clients',
  'analytics.metrics.returning': 'Returning',
  'analytics.metrics.retention': 'Retention',
  'analytics.noData': 'No data for selected period',
  // Financial analytics (B6)
  'analytics.financial.title': 'Financial Analytics',
  'analytics.financial.subtitle': 'Revenue, categories, forecast',
  'analytics.financial.revenue': 'Revenue',
  'analytics.financial.sessions': 'Sessions',
  'analytics.financial.avgTicket': 'Avg Ticket',
  'analytics.financial.topDay': 'Best Day',
  'analytics.financial.byCategory': 'By Category',
  'analytics.financial.peakHours': 'Peak Hours',
  'analytics.financial.forecast': '7-Day Forecast',
  'analytics.financial.confidence': 'Confidence',
  // Massage workload (B6)
  'analytics.massage.title': 'Massage Workload',
  'analytics.massage.subtitle': 'Track targets and manage overrides',
  'analytics.massage.total': 'Total Specialists',
  'analytics.massage.working': 'Working Today',
  'analytics.massage.meetingTarget': 'Meeting Target',
  'analytics.massage.belowTarget': 'Below Target',
  'analytics.massage.overridden': 'Override Active',
  'analytics.massage.alerts': 'Alerts',
  'analytics.massage.specialists': 'Specialists',

  // ─── Specialists ──────────────────────────────────────────────────────────────
  'specialists.title': 'Specialists',
  'specialists.add': 'Add Specialist',
  'specialists.new': 'New Specialist',
  'specialists.loading': 'Loading...',
  'specialists.empty': 'No specialists found',
  'specialists.filter.all': 'All',
  'specialists.filter.active': 'Active',
  'specialists.filter.inactive': 'Inactive',
  'specialists.status.active': 'Active',
  'specialists.status.vacation': 'On Leave',
  'specialists.status.inactive': 'Inactive',
  'specialists.status.dismissed': 'Dismissed',
  'specialists.deactivate': 'Deactivate',
  'specialists.restore': 'Restore',
  'specialists.experience': '{n} years experience',
  'specialists.profile': 'Specialist profile →',

  // ─── Services ─────────────────────────────────────────────────────────────────
  'services.title': 'Services',
  'services.active': 'Active',
  'services.total': 'Total',
  'services.add': 'New Service',
  'services.edit': 'Edit Service',
  'services.loading': 'Loading...',
  'services.empty': 'No services found',
  'services.hideInactive': 'Hide inactive',
  'services.showAll': 'Show all',
  'services.col.name': 'Name',
  'services.col.category': 'Category',
  'services.col.duration': 'Duration',
  'services.col.price': 'Price',
  'services.col.status': 'Status',
  'services.col.actions': 'Actions',
  'services.status.active': 'Active',
  'services.status.inactive': 'Inactive',
  'services.cat.cosmetology': 'Cosmetology',
  'services.cat.massage': 'Massage',
  'services.cat.injection': 'Injections',
  'services.cat.laser': 'Laser',
  'services.cat.body': 'Body Correction',
  'services.cat.epilation': 'Epilation',
  'services.cat.facial': 'Facial Care',
  'services.cat.other': 'Other',
  'services.cat.consultation': 'Consultation',

  // ─── Sales ────────────────────────────────────────────────────────────────────
  'sales.title': 'Sales',
  'sales.subtitle': 'Financial analytics and staff rankings',
  'sales.record': 'Record Sale',
  'sales.period.today': 'Today',
  'sales.period.7d': '7 days',
  'sales.period.30d': '30 days',
  'sales.period.90d': '90 days',
  'sales.metrics.revenue': 'Revenue for period',
  'sales.metrics.bookings': 'Bookings for period',
  'sales.metrics.avgTicket': 'Avg ticket',
  'sales.metrics.conversion': 'Conversion',
  'sales.metrics.clients': 'Unique clients',
  'sales.metrics.newClients': 'New clients',
  'sales.metrics.returning': 'Returning clients',
  'sales.chart.revenue': 'Revenue trend',
  'sales.chart.revenueHint': 'Confirmed and completed bookings',
  'sales.chart.bookings': 'Bookings by day',
  'sales.chart.bookingsHint': 'Number of confirmed bookings',
  'sales.ranking.title': 'Staff rankings',
  'sales.ranking.hint': 'By attributed revenue for period',
  'sales.noData': 'No data for selected period',
  'sales.noDataHint': 'Assign a salesperson when creating a booking',

  // ─── Inventory ────────────────────────────────────────────────────────────────
  'inventory.title': 'Inventory',
  'inventory.items': 'Items',
  'inventory.loading': 'Loading...',
  'inventory.add': 'Add',
  'inventory.movement': 'Movement',
  'inventory.edit': 'Edit',
  'inventory.tab.items': 'Items',
  'inventory.tab.alerts': 'Alerts',
  'inventory.tab.bindings': 'Consumable Bindings',
  'inventory.tab.analytics': 'Analytics',
  'inventory.filter.all': 'All categories',
  'inventory.search': 'Search by name, SKU, supplier...',
  'inventory.bindService': 'Bind consumable',
  'inventory.selectService': 'Select service',
  'inventory.selectItem': 'Select item',
  'inventory.status.ok': 'OK',
  'inventory.status.low': 'Low',
  'inventory.status.critical': 'Critical',
  'inventory.status.out': 'Out',
  'inventory.kpi.value': 'Inventory value',
  'inventory.kpi.lowStock': 'Low / Out',
  'inventory.kpi.expiring': 'Expiring (30d)',
  'inventory.cat.injectables': 'Injectables',
  'inventory.cat.skincare': 'Skincare',
  'inventory.cat.cosm': 'Cosmetology supplies',
  'inventory.cat.massageOils': 'Massage oils',
  'inventory.cat.massageSupp': 'Massage supplies',
  'inventory.cat.general': 'General supplies',
  'inventory.unit.ml': 'ml',
  'inventory.unit.pcs': 'pcs',
  'inventory.unit.g': 'g',
  'inventory.unit.kg': 'kg',
  'inventory.unit.l': 'l',
  'inventory.unit.pack': 'pack',
  'inventory.unit.pairs': 'pairs',
  'inventory.unit.roll': 'roll',

  // ─── Finance ──────────────────────────────────────────────────────────────────
  'finance.title': 'Financial Center',
  'finance.subtitle': 'Payments · Expenses · Reports · Export',
  'finance.tab.payments': 'Payments',
  'finance.tab.closing': 'Day Closing',
  'finance.tab.expenses': 'Expenses',
  'finance.tab.reports': 'Reports',
  'finance.tab.export': 'Export',
  'finance.refresh': 'Refresh',
  'finance.acceptPayment': 'Accept Payment',
  'finance.refund': 'Refund Payment',
  'finance.refundAction': 'Issue Refund',
  'finance.closeDate': 'Closing date',
  'finance.generate': 'Generate',
  'finance.revenueByMethod': 'Revenue by method',
  'finance.total.received': 'Received',
  'finance.total.refunded': 'Refunded',
  'finance.total.net': 'Net',
  'finance.total.transactions': 'Transactions',
  'finance.method.cash': 'Cash',
  'finance.method.card': 'Card',
  'finance.method.transfer': 'Transfer',
  'finance.method.yookassa': 'YooKassa',
  'finance.method.robokassa': 'Robokassa',
  'finance.method.internal': 'Internal',
  'finance.payStatus.unpaid': 'Unpaid',
  'finance.payStatus.deposit': 'Deposit',
  'finance.payStatus.partial': 'Partial',
  'finance.payStatus.paid': 'Paid',
  'finance.payStatus.refunded': 'Refunded',
  'finance.payStatus.failed': 'Failed',
  'finance.expense.purchase': 'Stock Purchase',
  'finance.expense.rent': 'Rent',
  'finance.expense.utilities': 'Utilities',
  'finance.expense.salary': 'Salary',
  'finance.expense.operational': 'Operational',
  'finance.expense.marketing': 'Marketing',
  'finance.expense.other': 'Other',

  // ─── Settings ─────────────────────────────────────────────────────────────────
  'settings.title': 'Settings',
  'settings.subtitle': 'Personalization and system parameters',
  'settings.section.interface': 'Appearance',
  'settings.section.interfaceSub': 'Interface, theme and density',
  'settings.uiMode': 'Interface Mode',
  'settings.uiModeSub': 'Choose your workspace',
  'settings.classic': 'Classic CRM',
  'settings.luxury': 'Luxury Executive',
  'settings.colorTheme': 'Color Theme',
  'settings.colorThemeSub': 'Applies to both modes',
  'settings.dark': 'Dark',
  'settings.light': 'Light',
  'settings.density': 'Density',
  'settings.comfortable': 'Comfortable',
  'settings.compact': 'Compact',
  'settings.language': 'Language',
  'settings.langRu': 'Russian',
  'settings.langEn': 'English',
  'settings.section.notifications': 'Client Notifications',
  'settings.section.specialistNotif': 'Specialist Notifications',
  'settings.notif.confirmation': 'Booking confirmation',
  'settings.notif.reminder': '24-hour reminder',
  'settings.notif.cancellation': 'Cancellation notice',
  'settings.notif.sms': 'SMS notifications',
  'settings.notif.newBooking': 'New booking',
  'settings.notif.cancelReschedule': 'Cancellation or rescheduling',
  'settings.notif.morningBrief': 'Morning briefing',
  'settings.section.payment': 'Payment',
  'settings.payment.cash': 'Cash',
  'settings.payment.terminal': 'Card terminal',
  'settings.payment.online': 'Online payment',
  'settings.section.about': 'About Studio',
  'settings.section.security': 'Security',
};

const TRANSLATIONS: Record<Lang, Record<string, string>> = { ru: RU, en: EN };

const LanguageContext = React.createContext<LanguageCtx>({
  lang: 'ru',
  setLang: () => {},
  t: (k) => k,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = React.useState<Lang>('ru');

  React.useEffect(() => {
    try {
      const stored = localStorage.getItem('lang') as Lang;
      if (stored === 'en' || stored === 'ru') setLangState(stored);
    } catch {}
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    try { localStorage.setItem('lang', l); } catch {}
  };

  const t = (key: string): string => TRANSLATIONS[lang][key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return React.useContext(LanguageContext);
}
